openapi: 3.0.3
info:
  title: Api Documentation
  description: Api Documentation
  version: '1.0'
servers:
  - url: http://localhost:8080
    description: Inferred Url
tags:
  - name: versions-controller
    description: Versions Controller
paths:
  /api/tdm/versions/backend:
    get:
      tags:
        - versions-controller
      summary: getBackendVersion
      operationId: getBackendVersion
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Version'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
components:
  schemas:
    Version:
      title: Version
      type: object
      properties:
        name:
          type: string
        version:
          type: string
