apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.SERVICE_NAME }}-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.atp3tdm.storageSize }}
  storageClassName: {{ .Values.atp3tdm.storageClassName }}