# Which docker image should be used to deploy
DOCKER_TAG: ""
# This option turns on or off logging in graylog
GRAYLOG_ON: "false"
keepHookLogs: true
HELPER_IMAGE: "ghcr.io/netcracker/qubership-testing-platform-helm-hook-helper:main_latest"
CONTENT_SECURITY_POLICY: "*"